config/routes.rb
Rails.application.routes.draw do
  resources :comments

  resources :activities, only: [:index]

  get 'members/list'

  get 'members/search'

  as :user do 
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :user_friendships do
    member do
      post :accept
      get :accept
      get "/block" => "user_friendship#block"
      post "/block" => "user_friendship#block"
      get "/destroy" => "user_friendships#destroy"
      post "/destroy" => "user_friendships#destroy"
    end
    collection do
      get "feed" => "user_friendships#feed"
      post "feed" => "user_friendships#feed"
    end
  end

  resources :statuses

  get 'feed', to: 'statuses#index', as: :feed
  get 'feed/create', to: 'statuses#new', as: :feed_create

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  root to: 'activities#index'

  
  scope ":profile_name" do
    resources :albums do
      resources :pictures
    end
  end

  get '/:id', to: 'profiles#show', as: 'profile'

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
end

app/controllers/statuses_controller.rb
require 'simple_format'


class StatusesController < ApplicationController
before_filter :authenticate_user!, only: [:show, :create, :new, :edit, :update, :destroy]
before_action :set_status, only: [:show, :edit, :update, :destroy]

#rescue_from ActiveModel::MassAssignmentSecurity::Error, with: :render_permission_error


  # GET /statuses
  # GET /statuses.json
  def index
    params[:page] ||= 1
    @statuses = Status.for_user(current_user, params)
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
    @comment = Comment.new
    @comment.build_document
  end

  # GET /statuses/new
  def new
    @status = Status.new
    @status.build_document
  end

  # GET /statuses/1/edit
  def edit
    if !@status.document
      @status.build_document
    end
  end

  # POST /statuses
  # POST /statuses.json
  def create
    c = SimpleFormat::Converter.new
    @status = current_user.statuses.new(status_params)
    @status[:content] = c.rich_with(@status[:content])
    respond_to do |format|
      if @status.save
        current_user.create_activity(@status,'created')
        format.html { redirect_to root_path, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    c = SimpleFormat::Converter.new
    @status = current_user.statuses.find(params[:id])
    @status[:content] = c.rich_with(@status[:content])
    
    if status_params && status_params.has_key?(:user_id)
      status_params.delete(:user_id)
    end

    if status_params.has_key?(:document_attributes) && params[:status][:document_attributes][:remove_attachment] == '1'
      @status.document.attachment = nil
    else
      if @status.document && @status.document.attachment? && status_params.has_key?(:document_attributes)
        status_params.delete(:document_attributes)
      end
    end

    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:content, :id, :status, :profile_name, :full_name, :user_id, :first_name, :last_name, document_attributes: document_permitted_attributes)
    end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.erb
<%= simple_form_for(@status, html: {class: "well", role: "form", multipart: true}) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>
    <legend>Status</legend>

  <%= f.input :content,label: false, input_html:{class: "form-control auto-focus", rows: "10", autofocus: ""}, wrapper_html:{class: "form-group"} %><br>
  <%= f.fields_for :document do |document_fields| %>
    <% if document_fields.object.attachment? %>
      <%= document_fields.input :remove_attachment, as: :boolean, label: "Remove attachment?", label_html: {style: "float:left;"}, input_html: {style: "margin-left: 5px"} %>
      <div class="control-group">
        <label class="control-label">Current picture</label>
        <div class="controls">
          <%= status_document_link @status %>
        </div>
      </div>
    <% else %>
      <%= document_fields.input :attachment, as: :file, label: "Add Picture" %>
    <% end %>
  <% end %>
  
  <div class="form-actions" style="margin-top: 10px;">
    <%= button_tag(type: 'submit', class: "btn btn-success") do %>
        Post
    <% end %>
  </div>
  </fieldset>
<% end %>

app/views/statuses/edit.html.erb
<% if @status.user_id == current_user.id then %>

<h1>Editing status</h1>

<%= render 'form' %>
<% end %>
<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<% if user_signed_in? %>
<div class="col-md-2 well hidden-sm hidden-xs" style="position: fixed; left:10px; height: 100%;">
    <h3>Where are the avatars from?</h3>
    <div class="h5">
        You can add an avatar by <%= link_to "editing your profile here and adding one", edit_user_registration_path %>, or by adding one to your e-mail address at <a href="http://www.gravatar.com">Gravatar</a> that can be used on multiple websites!</div>

    <div class="h5">
          If you don't have one you can <a href="www.gravatar.com">go set one up</a>, its easy!
    </div>
</div>
<div class="col-md-2">
 
</div>
<div class="col-md-8">

<div>
    <h1>Your friends' statuses: </h1>
</div>

<%= link_to "Post a New Status", feed_create_path, class: "btn btn-primary" %>

<% @statuses.each do |status| %>
<% if can_display_status?(status) %>
    <div class="status">
     <div class="row">
      <div class="col-md-2">
        <%= avatar_profile_link status.user, {class: 'img-circle'}, class: 'pull-left' %>
      </div>
      <div class="col-md-10">
        <strong><%= link_to status.user.full_name, profile_path(status.user) %></strong>
        <p><%= replace_smilies(status.content.html_safe, true) %></p>
        <%= image_link_to_status(status) %>
        <div class="meta">
            <%= link_to time_ago_in_words(status.created_at).concat(" ago"), status %>
            <span class="admin">
            <% if status.user_id == current_user.id %>
                | <%= link_to "Edit", edit_status_path(status) %> |
                <%= link_to "Delete", status, method: :delete, data: { confirm: "Are you sure you want to delete this status?" } %>
            <% end %>
            </span>
        </div>
      </div>
     </div>
    </div>
<% end %>
<% end %>
<%= will_paginate @statuses %>
</div>
<div class="col-md-2 well hidden-sm hidden-xs" style="position: fixed; float:right; right: 10px; height:100%;">

    <h3>Advertisements:</h3>
    
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<div style="margin: 0 auto; text-align: center;">
<!-- my world ads -->
      <ins class="adsbygoogle" style="display:inline-block;width:120px;height:240px" data-ad-client="ca-pub-4879610818531401" data-ad-slot="8250066063"></ins>

      <script>
        (adsbygoogle = window.adsbygoogle || []).push({});
      </script>
</div>
    <div class="h5">We know ads aren't cool, but you've got to make a living somehow, right?</div>

</div>
<% else %>
<div class="col-md-4">
  <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name), html: {class: "well"}) do |f| %>
    <fieldset>
      <legend>Sign up!</legend>
      <%= devise_error_messages! %>

      <div><%= f.input :first_name, autofocus: true %></div>

      <div><%= f.input :last_name %></div>

      <div><%= f.input :profile_name %></div>

      <div><%= f.input :email %></div>

      <div><%= f.input :password, autocomplete: "off" %></div>

      <div><%= f.input :password_confirmation, autocomplete: "off" %></div>

      <div>
        <%= button_tag(type: 'submit', class: "btn btn-success") do %>
          Register
        <% end %>
      </div>
    </fieldset>
  <% end %>
</div>
<div class="col-md-4">
  <h2>Join MyWorldtoGo now!</h2>
  <div>
    MyWorldtoGo is the new social network where we don't track how many times you poke someone, or details other than the normal stuff in the database that makes the software work!
  </div>
</div>
<div class="col-md-4">
  <%= simple_form_for(:user, :url => session_path(:user), html: {class: "well", role: "form"}) do |f| %>
    <fieldset>
      <legend>Already a member? Log in now:</legend>
      <%= f.input :email, wrapper_html: {class: "form-group"}, input_html: {class: "form-control", placeholder: "E-mail"}, label: false %>
      <%= f.input :password, wrapper_html:{class: "form-group"}, input_html: {class: "form-control", placeholder: "Password"}, label: false %>
      <%= button_tag(type: 'submit', class: "btn btn-success") do %>
        Log in
      <% end %>
    </fieldset>
    <%= render "devise/shared/links" %>
  <% end %>
</div>
<% end %>

app/views/statuses/new.html.erb
<div class="col-md-6">
<%= render 'form' %>

<%= link_to 'Back', statuses_path %>
</div>
<div class="col-md-6">
<h2>Enter your new status</h2>
You might include things like where you are at, what you are doing, or maybe even personal thoughts, or a quote for the day.  Your status is your own, whatever you want to put there is up to you.
<h3>MyWorldtoGo.com, making the world a smaller place, without selling your information</h3>
</div>

app/views/statuses/show.html.erb
<div class="row">
  <div class="col-md-8 offset2">
    <%= page_header do %>
      <h1>
        <%= avatar_profile_link @status.user, {class: 'img-circle'} %>
        <%= @status.user.full_name %>
        <small><%= time_ago_in_words(@status.created_at) + " ago" %></small>
      </h1>
    <% end %>
    
    <p>
      <%= replace_smilies(@status.content, true) %>
    </p>
    
    <hr />
    
    <% if @status.document && @status.document.attachment? %>
      <%= status_document_link @status %>
      <hr />
    <% end %>
    
    <div class="meta">
      
      <%= link_to 'Back', activities_path %>
      <% if signed_in? && @status.user_id == current_user.id then %>
          |
        <%= link_to 'Edit', edit_status_path(@status) %> |
        <%= link_to 'Delete', @status, method: :delete, data: {confirm: "Are you sure you want to delete this status?"} %>
      <% end %>
    </div>
    <%= simple_form_for(@comment, html: {class: "well", role: "form", multipart: true}) do |f| %>
          <% @comments = Comment.where("parent_type = 'status' AND parent_id = " + @status.id.to_s).order("created_at") %>
          <ul class="media-list">
            <% @comments.each do |comment| %>
              <li class="media">
                <%= avatar_profile_link comment.user, {class: 'img-circle pull-left', width: '30px', height: '30px'} %>
                <div class="media-body">
                  <h5 class="media-heading">
                    <%= link_to comment.user.full_name, profile_path(comment.user) %>
                    <% if User.online.include?(comment.user) %>
                      <span style="color: #29aa09;">Online</span>
                    <% end %>
                  </h5>
                  <%= replace_smilies(comment.content.html_safe, true) %>
                  <p><%= image_link_to_status(comment) %><p>
                  <p><small><%= time_ago_in_words(comment.created_at) %> ago</small></p>
                </div>
              </li>
              <hr style="margin-top: 2px; margin-bottom: 2px;">
            <% end %>
          </ul>
        <%= f.error_notification %>

        <div class="form-inputs">

          <%= f.input :parent_type, as: :hidden, input_html: {value: 'status'} %>
          <%= f.input :parent_id, as: :hidden, input_html: {value: @status.id} %>
          <%= f.input :content, label: false, input_html: {class: 'form-control', placeholder: "Add a comment..."} %>

        </div>
        <%= f.fields_for :document do |document_fields| %>
          <% if document_fields.object.attachment? %>
            <%= document_fields.input :remove_attachment, as: :boolean, label: "Remove attachment?", label_html: {style: "float:left;"}, input_html: {style: "margin-left: 5px"} %>
            <div class="control-group">
              <label class="control-label">Current picture</label>
              <div class="controls">
                <%= status_document_link @comment %>
              </div>
            </div>
          <% else %>
            <div class="pull-left"><%= document_fields.input :attachment, as: :file, label: false, input_html: {accept: "image/*", value: "Add Picture"} %></div>
          <% end %>
        <% end %>
        <div class="form-actions">
          <%= button_tag(type: 'submit', class: "btn btn-success pull-right") do %>
              Add Comment
          <% end %>
        </div>
      <% end %>
  </div>
</div>