config/routes.rb
Rails.application.routes.draw do
  resources :comments

  resources :activities, only: [:index]

  get 'members/list'

  get 'members/search'

  as :user do 
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :user_friendships do
    member do
      post :accept
      get :accept
      get "/block" => "user_friendship#block"
      post "/block" => "user_friendship#block"
      get "/destroy" => "user_friendships#destroy"
      post "/destroy" => "user_friendships#destroy"
    end
    collection do
      get "feed" => "user_friendships#feed"
      post "feed" => "user_friendships#feed"
    end
  end

  resources :statuses

  get 'feed', to: 'statuses#index', as: :feed
  get 'feed/create', to: 'statuses#new', as: :feed_create

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  root to: 'activities#index'

  
  scope ":profile_name" do
    resources :albums do
      resources :pictures
    end
  end

  get '/:id', to: 'profiles#show', as: 'profile'

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :user
  belongs_to :targetable, polymorphic: true
  
  self.per_page = 30
  
  def self.for_user(user, options={})
    options[:page] ||=1
    friend_ids = user.friends.map(&:id).push(user.id)
    active_users = User.all.map(&:id)
    collection = where("user_id in (?) AND targetable_type != ? AND user_id in (?)", friend_ids, 'Comment', active_users).
      order("updated_at DESC")
    if options[:since] && !options[:since].blank?
      since = DateTime.strptime( options[:since], '%s')
      collection = collection.where("updated_at > ? AND user_id in (?)", since, active_users) if since
    end
      collection.page(options[:page])
  end
  
  def self.for_user_notifications(user, options={})
    options[:page] ||=1
    friend_ids = user.friends.map(&:id)
    active_users = User.all.map(&:id)
    collection = where("user_id in (?)", friend_ids).
      order("created_at DESC")
    if options[:since] && !options[:since].blank?
      since = DateTime.strptime( options[:since], '%s')
      collection = collection.where("updated_at > ? AND user_id in (?)", since, active_users) if since
    end
      collection.page(options[:page])
  end
  
  def user_name
    user.full_name
  end
  
  def profile_name
    user.profile_name
  end
  
  def user_avatar
    user.avatar_image_url
  end
  
  def as_json(options={})
    super(
      only: [:action, :id, :targetable_id, :targetable_type, :created_at, :id],
      include: :targetable,
      methods: [:user_name, :profile_name, :user_avatar]
    ).merge(options)
  end
end

app/models/status.rb
class Status < ActiveRecord::Base
    
    belongs_to :user
    belongs_to :document
    
    accepts_nested_attributes_for :document

    validates :content, presence: true,
                  length: {minimum: 2}

    validates :user_id, presence: true
    
    self.per_page = 30
  
    def self.for_user(user, options={})
        options[:page] ||=1
        friend_ids = user.friends.map(&:id).push(user.id)
        where("user_id in (?)", friend_ids).
          order("created_at DESC").
          page(options[:page])
    end

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  respond_to :html, :json
  
  def index
    if signed_in?
      params[:page] ||= 1
      respond_to do |format|
        format.html do
          @activities = Activity.for_user(current_user, params)
        end
        format.json do
          @activities = Activity.for_user_notifications(current_user, params)
        end
      end
      @comment = Comment.new
      @comment.build_document
      @status = Status.new
      @status.build_document
      
      respond_with @activities
    else
      @activities = {};
    end
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/status/_created.html.erb
<p>Created a new
<% if activity.targetable %>
  <%= link_to "status", status_path(activity.targetable_id) %></p>
  <p><%= replace_smilies(activity.targetable.content.html_safe, true) %></p>
  <%= image_link_to_status(activity.targetable) %>
  <div class="meta" style="height:15px;">
      <span class="admin">
      <% if activity.targetable.user_id == current_user.id %>
          <%= link_to "Edit", edit_status_path(activity.targetable) %> |
          <%= link_to "Delete", activity.targetable, method: :delete, data: { confirm: "Are you sure you want to delete this status?" } %>
      <% end %>
      </span>
  </div>
<% else %>
  status.</p>
<% end %>

app/views/activities/status/_updated.html.erb
<p>Updated a
<% if activity.targetable %>
  <%= link_to "status", status_path(activity.targetable_id) %></p>
  <p><%= replace_smilies(activity.targetable.content.html_safe, true) %></p>
  <%= image_link_to_status(activity.targetable) %>
  <div class="meta" style="height:15px;">
      <span class="admin">
      <% if activity.targetable.user_id == current_user.id %>
          <%= link_to "Edit", edit_status_path(activity.targetable) %> |
          <%= link_to "Delete", activity.targetable, method: :delete, data: { confirm: "Are you sure you want to delete this status?" } %>
      <% end %>
      </span>
  </div>
<% else %>
  status.</p>
<% end %>