config/routes.rb
Rails.application.routes.draw do
  resources :comments

  resources :activities, only: [:index]

  get 'members/list'

  get 'members/search'

  as :user do 
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :user_friendships do
    member do
      post :accept
      get :accept
      get "/block" => "user_friendship#block"
      post "/block" => "user_friendship#block"
      get "/destroy" => "user_friendships#destroy"
      post "/destroy" => "user_friendships#destroy"
    end
    collection do
      get "feed" => "user_friendships#feed"
      post "feed" => "user_friendships#feed"
    end
  end

  resources :statuses

  get 'feed', to: 'statuses#index', as: :feed
  get 'feed/create', to: 'statuses#new', as: :feed_create

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  root to: 'activities#index'

  
  scope ":profile_name" do
    resources :albums do
      resources :pictures
    end
  end

  get '/:id', to: 'profiles#show', as: 'profile'

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :album
  belongs_to :user
  has_attached_file :asset, styles: {
        original: "1200x1200>", large: "800x800>", medlg: "500x600>", medium: "300x200>", small: "260x180>", mos: "200x135#", thumb: "80x80#"
    }
  
  def to_s
    caption? ? caption : "Picture"
  end
  
  validates_attachment_content_type :asset, :content_type => /\Aimage\/.*\Z/
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_filter :authenticate_user!, only: [:show, :new, :create, :edit, :update, :destroy]
  before_filter :find_user
  before_filter :find_album
  before_filter :find_picture, only: [:edit, :update, :show, :destroy]
  before_filter :ensure_proper_user, only: [:edit, :update, :destroy, :new, :create]
  before_filter :only_friends
  before_filter :add_breadcrumbs
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = @album.pictures.all
    @comment = Comment.new
    @comment.build_document
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    @picture = @album.pictures.find(params[:id])
    add_breadcrumb @picture, album_picture_path(@album, @picture)
    @comment = Comment.new
    @comment.build_document
  end

  # GET /pictures/new
  def new
    @picture = @album.pictures.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @picture }
    end
    add_breadcrumb "Adding new picture"
  end

  # GET /pictures/1/edit
  def edit
    add_breadcrumb @picture, album_picture_path(@album, @picture)
    add_breadcrumb "Editing Picture"
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = @album.pictures.new(picture_params)
    @picture.user = current_user

    respond_to do |format|
      if @picture.save
        current_user.create_activity(@album,'addedpictures')
        format.html { redirect_to album_pictures_path(@album), notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        current_user.create_activity(@album,'updatedpictures')
        format.html { redirect_to album_pictures_path(@album), notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to album_pictures_path(@album) }
      format.json { head :no_content }
    end
  end

  def url_options
    { profile_name: params[:profile_name] }.merge(super)
  end

  private
    def ensure_proper_user
      if current_user != @user
        flash[:error] = "You don't have permission to do that."
        redirect_to album_pictures_path
      end
    end
  
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:album_id, :user_id, :caption, :description, :asset, asset_attributes: asset_permitted_attributes)
    end
    
    def add_breadcrumbs
      add_breadcrumb @user.first_name, profile_path(@user)
      add_breadcrumb "Albums", albums_path(@user)
      add_breadcrumb @album.title, album_pictures_path(@album)
    end
    
    def find_user
      @user = User.find_by_profile_name(params[:profile_name])
    end
    
    def find_album
      if signed_in? && current_user.profile_name == params[:profile_name]
        @album = current_user.albums.find(params[:album_id])
      else
        @album = @user.albums.find(params[:album_id])
      end
    end
    
    def find_picture
      @picture = @album.pictures.find(params[:id])
    end
    
    def only_friends
      unless @user.friends.include?(current_user) || @user == current_user
        flash[:error] = "You need to be friends to view a user's albums, you can request the friendship on this page."
        redirect_to profile_path(@user)
      end
    end
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def can_edit_picture?(picture)
    signed_in? && current_user == picture.user
  end
end

app/views/pictures/_form.html.erb
<div class="col-md-6">
  <%= simple_form_for([@album, @picture], html: {class: 'form-horizontal'}) do |f| %>
    <%= f.error_notification %>
  
    <div class="form-group">
      <%= f.input :asset, as: :file, input_html: { class: 'form-control' }, label: 'Picture' %>
      <%= bootstrap_paperclip_picture f, :asset %>
      <%= f.input :caption, input_html: { class: 'form-control' } %>
      <%= f.input :description, input_html: { class: 'form-control', rows: 4 } %>
    </div>
  
    <div class="form-actions">
      <%= f.button :submit, class: 'btn btn-default' %>
    </div>
  <% end %>
</div>
<div class="col-md-3">
   
</div>
<div class="col-md-3">
   
</div>

app/views/pictures/edit.html.erb
<h1>Editing picture</h1>

<%= render 'form' %>

<%= link_to 'Show', album_picture_path(@album, @picture) %> |
<%= link_to 'Back', album_pictures_path(@album) %>

app/views/pictures/index.html.erb
<div class="col-md-1">

</div>
<div class="col-md-10">
<div style="width: 100%; margin: 0 auto 0 auto;">
  <% if signed_in? && current_user == @user %>
    <%= link_to 'Add Picture', new_album_picture_path(current_user, @album), class: 'btn pull-right btn-primary' %>
  <% end %>
  <h1 style="margin-top: 0;"><%= @album.title %></h1>
    <div class="mosaiqy" style="width: 100%; margin: 0 auto 0 auto; padding-bottom: 10px;">
        <ul style="padding: 0 5%;">
          <% @pictures.each do |picture| %>
            <li style="top: 0px; left: 0px; -webkit-transition: 1.2s; transition: 1.2s; float: left;">
            <div>
              <figure style="position: relative;">
                <a href="<%= album_picture_path(@user, @album, picture) %>"><img src="<%= picture.asset.url(:mos) %>" style="opacity: 1;">
                  <div>
                    <figcaption style="float:left; position: absolute;">
                      <h4 style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis;">
                        <% if picture.caption? %>
                          <%= picture.caption %>
                        <% else %>
                          No Caption
                        <% end %>
                      </h4>
                      <hr style="color: #28287A; background-color: #28287A; height: 2px;">
                      <div style="height: 63px; display: block; overflow: hidden; text-overflow: ellipsis;">
                        <% if picture.description? %>
                          <%= picture.description %>
                        <% end %>
                      </div>
                      <% if can_edit_picture?(picture) %>
                        <%= link_to 'Edit', edit_album_picture_path(@album, picture), class: "btn btn-primary", style: "height: 24px; width:40%; position: absolute; bottom: 5px; left: 10px;", role: "button" %>
                        <%= link_to 'Delete', album_picture_path(@album, picture), method: :delete, data: {confirm: "Are you sure you want to delete this picture?" }, class: "btn btn-danger", style: "height: 24px; width:40%; position: absolute; bottom: 5px; right: 10px;", role: "button" %>
                      <% else %>
                        <%= link_to 'View Album', album_picture_path(@user, @album, picture), class: "btn btn-primary", style: "height: 24px; width:80%; position: absolute; bottom: 5px; left: 20px;", role: "button" %>
                      <% end %>
                    </figcaption>
                  </div>
                </a>
              </figure>
            </div>
          </li>
          <% end %>
        </ul>
    </div>
<%= simple_form_for(@comment, html: {class: "well", role: "form", multipart: true, style: "padding-bottom: 43px;"}) do |f| %>
<% @comments = Comment.where("parent_type = 'album' AND parent_id = " + @album.id.to_s).order("created_at") %>
<ul class="media-list">
<% @comments.each do |comment| %>
  <li class="media">
    <%= avatar_profile_link comment.user, {class: 'img-circle pull-left', width: '30px', height: '30px'} %>
    <div class="media-body">
      <h5 class="media-heading">
        <%= link_to comment.user.full_name, profile_path(comment.user) %>
        <% if User.online.include?(comment.user) %>
          <span style="color: #29aa09;">Online</span>
        <% end %>
      </h5>
      <%= replace_smilies(comment.content.html_safe, true) %>
      <p><%= image_link_to_status(comment) %><p>
      <p><small><%= time_ago_in_words(comment.created_at) %> ago</small></p>
    </div>
  </li>
  <hr style="margin-top: 2px; margin-bottom: 2px;">
<% end %>
</ul>
<%= f.error_notification %>

<div class="form-inputs">

<%= f.input :parent_type, as: :hidden, input_html: {value: 'album'} %>
<%= f.input :parent_id, as: :hidden, input_html: {value: @album.id} %>
<%= f.input :content, label: false, input_html: {class: 'form-control', placeholder: "Add a comment..."} %>

</div>
<%= f.fields_for :document do |document_fields| %>
  <% if document_fields.object.attachment? %>
    <%= document_fields.input :remove_attachment, as: :boolean, label: "Remove attachment?", label_html: {style: "float:left;"}, input_html: {style: "margin-left: 5px"} %>
    <div class="control-group">
      <label class="control-label">Current picture</label>
      <div class="controls">
        <%= status_document_link @comment %>
      </div>
    </div>
  <% else %>
    <div class="pull-left"><%= document_fields.input :attachment, as: :file, label: false, input_html: {accept: "image/*", value: "Add Picture"} %></div>
  <% end %>
<% end %>
<div class="form-actions">
  <%= button_tag(type: 'submit', class: "btn btn-success pull-right") do %>
      Add Comment
  <% end %>
</div>
<% end %>
</div>
</div>
<div class="col-md-1">

</div>

app/views/pictures/new.html.erb
<h1>New picture</h1>

<%= render 'form' %>

<%= link_to 'Back', album_pictures_path(@album) %>

app/views/pictures/show.html.erb
<div class="col-md-1">

</div>
<div class="col-md-10">
  <div style="margin: 0 auto; position: relative;">
    <h1 style="margin-top: 0; text-align: center;">Viewing Picture</h1>
    <div style="display: block; margin: 0 auto; width: auto; max-width: 600px; text-align: center;">
      <%= link_to image_tag(@picture.asset.url(:medlg), alt: @picture.caption, class: 'img-polaroid'), @picture.asset.url(:original), :target => "_blank" %>
      <br />

      <h3><%= @picture.caption %></h3>

      <p><%= @picture.description %></p>

      <%= link_to 'Edit', edit_album_picture_path(@album, @picture) %> |
      <%= link_to 'Album', album_pictures_path(@album) %>
    </div>
    <div style="height: 104px; padding: 2px; border: 1px solid #e3e3e3; overflow-x: scroll; overflow-y: hidden; margin-bottom: 10px; margin-top: 10px; text-align: center; white-space: nowrap;">
      <% album_thumbnail(@album, true, 0).each do |item| %>
        <%= link_to item[:image], album_picture_path(@user, @album, item[:picture]) %>
      <% end %>
    </div>
    <%= simple_form_for(@comment, html: {class: "well", role: "form", multipart: true, style: "padding-bottom: 43px;"}) do |f| %>
    <% @comments = Comment.where("parent_type = 'picture' AND parent_id = " + @picture.id.to_s).order("created_at") %>
    <ul class="media-list">
    <% @comments.each do |comment| %>
      <li class="media">
        <%= avatar_profile_link comment.user, {class: 'img-circle pull-left', width: '30px', height: '30px'} %>
        <div class="media-body">
          <h5 class="media-heading">
            <%= link_to comment.user.full_name, profile_path(comment.user) %>
            <% if User.online.include?(comment.user) %>
              <span style="color: #29aa09;">Online</span>
            <% end %>
          </h5>
          <%= replace_smilies(comment.content.html_safe, true) %>
          <p><%= image_link_to_status(comment) %><p>
          <p><small><%= time_ago_in_words(comment.created_at) %> ago</small></p>
        </div>
      </li>
      <hr style="margin-top: 2px; margin-bottom: 2px;">
    <% end %>
    </ul>
    <%= f.error_notification %>

    <div class="form-inputs">

    <%= f.input :parent_type, as: :hidden, input_html: {value: 'picture'} %>
    <%= f.input :parent_id, as: :hidden, input_html: {value: @picture.id} %>
    <%= f.input :content, label: false, input_html: {class: 'form-control', placeholder: "Add a comment..."} %>

    </div>
    <%= f.fields_for :document do |document_fields| %>
          <% if document_fields.object.attachment? %>
            <%= document_fields.input :remove_attachment, as: :boolean, label: "Remove attachment?", label_html: {style: "float:left;"}, input_html: {style: "margin-left: 5px"} %>
            <div class="control-group">
              <label class="control-label">Current picture</label>
              <div class="controls">
                <%= status_document_link @comment %>
              </div>
            </div>
          <% else %>
            <div class="pull-left"><%= document_fields.input :attachment, as: :file, label: false, input_html: {accept: "image/*", value: "Add Picture"} %></div>
          <% end %>
        <% end %>
        <div class="form-actions">
          <%= button_tag(type: 'submit', class: "btn btn-success pull-right") do %>
              Add Comment
          <% end %>
        </div>
    
    <% end %>
  </div>
</div>
<div class="col-md-1">

</div>